import { Banknote, Boxes, Calculator, Combine, FileText, LayoutDashboard, ShoppingCart, Wrench } from "lucide-react";

export const EXAMPLE_PACKAGES_DATA = [
  {
    description: [
      { id: 1, text: "Unlimited Photos" },
      { id: 2, text: "High-Resolution Images" },
      { id: 3, text: "Photo Editing" },
      { id: 4, text: "Online Gallery" },
      { id: 5, text: "Prints Available" },
    ],
    id: 1,
    price: "5000000",
    title: "PHOTOGRAPHY BASIC",
  },
  {
    description: [
      { id: 1, text: "Unlimited Photos" },
      { id: 2, text: "High-Resolution Images" },
      { id: 3, text: "Photo Editing" },
      { id: 4, text: "Online Gallery" },
      { id: 5, text: "Prints Available" },
      { id: 6, text: "Photo Album" },
    ],
    id: 2,
    price: "7000000",
    title: "PHOTOGRAPHY STANDARD",
  },
  {
    description: [
      { id: 1, text: "Unlimited Photos" },
      { id: 2, text: "High-Resolution Images" },
      { id: 3, text: "Photo Editing" },
      { id: 4, text: "Online Gallery" },
      { id: 5, text: "Prints Available" },
      { id: 6, text: "Photo Album" },
      { id: 7, text: "Framed Prints" },
    ],
    id: 3,
    price: "10000000",
    title: "PHOTOGRAPHY PREMIUM",
  },
  {
    description: [
      { id: 1, text: "Unlimited Photos" },
      { id: 2, text: "High-Resolution Images" },
      { id: 3, text: "Photo Editing" },
      { id: 4, text: "Online Gallery" },
      { id: 5, text: "Prints Available" },
      { id: 6, text: "Photo Album" },
      { id: 7, text: "Framed Prints" },
      { id: 8, text: "Custom Photo Book" },
    ],
    id: 4,
    price: "15000000",
    title: "PHOTOGRAPHY ULTIMATE",
  },
  {
    description: [
      { id: 1, text: "Full HD Video" },
      { id: 2, text: "Video Editing" },
      { id: 3, text: "Highlight Reel" },
      { id: 4, text: "Online Delivery" },
      { id: 5, text: "DVD Copy" },
    ],
    id: 5,
    price: "8000000",
    title: "VIDEOGRAPHY BASIC",
  },
  {
    description: [
      { id: 1, text: "Full HD Video" },
      { id: 2, text: "Video Editing" },
      { id: 3, text: "Highlight Reel" },
      { id: 4, text: "Online Delivery" },
      { id: 5, text: "DVD Copy" },
      { id: 6, text: "Drone Footage" },
    ],
    id: 6,
    price: "12000000",
    title: "VIDEOGRAPHY STANDARD",
  },
  {
    description: [
      { id: 1, text: "Full HD Video" },
      { id: 2, text: "Video Editing" },
      { id: 3, text: "Highlight Reel" },
      { id: 4, text: "Online Delivery" },
      { id: 5, text: "DVD Copy" },
      { id: 6, text: "Drone Footage" },
      { id: 7, text: "Custom USB Drive" },
    ],
    id: 7,
    price: "18000000",
    title: "VIDEOGRAPHY PREMIUM",
  },
  {
    description: [
      { id: 1, text: "Full HD Video" },
      { id: 2, text: "Video Editing" },
      { id: 3, text: "Highlight Reel" },
      { id: 4, text: "Online Delivery" },
      { id: 5, text: "DVD Copy" },
      { id: 6, text: "Drone Footage" },
      { id: 7, text: "Custom USB Drive" },
      { id: 8, text: "Feature Film" },
    ],
    id: 8,
    price: "25000000",
    title: "VIDEOGRAPHY ULTIMATE",
  },
];

export const MENU_DATA = [
  {
    icon: Wrench,
    label: "Maintenance",
    subItems: [
      "Administrasi Pengguna Aplikasi",
      "Daftar Relasi",
      {
        children: ["Daftar Customer", "Histori Peralihan Customer", "Histori Membership Customer", "Pengajuan Aktivasi dan Open Blacklist"],
        label: "Customer",
      },
      "Supplier",
      "Salesman",
      {
        children: [
          "Setting Batas Bayar dan Pembelian Produk",
          "Setting Pendapatan Insentif",
          "Setting Target Distribusi",
          "Setting Target Penagihan",
          "Setting Model Insentif",
          "Setting Denda dan Potongan",
          "Setting Minimal Target Penjualan",
        ],
        label: "Produk dan Insentif",
      },
      "Daftar Akun",
      "Anggaran Akun",
      "Akun Pembantu (Subledger)",
      "Departemen",
      "Aktiva Tetap (Asset)",
      "Daftar Persediaan",
      {
        children: [
          "Harga Pembelian Per Item",
          "Harga Pembelian Per Supplier",
          "Harga Penjualan Per Item",
          "Harga Penjualan Per Customer",
          "Harga Ekspedisi",
        ],
        label: "Daftar Harga",
      },
      {
        children: [
          "Gudang",
          "Kurs Mata Uang",
          "Pajak",
          "Termin Pembayaran",
          "Rayon (Wilayah Penjualan)",
          "Kendaraan",
          "Pengemudi (Sopir)",
          "Via Pengiriman (Ekspedisi)",
          "Bank",
          "Area dan Biaya Pengiriman",
          "Diskon Tonase",
          "Kategori",
          "Kelompok Produk",
          "Merek Produk",
          "Hari Libur",
          "Alasan",
          "Propinsi dan Kota",
          "Kecamatan dan Kelurahan",
          "Data Legalitas Ekspedisi",
          "Klasifikasi Plafond Maksimal",
          "Wilayah dan Biaya Kirim",
        ],
        label: "Daftar Lainnya",
      },
      "Daftar Karyawan",
      "Daftar Divisi Penjualan",
      "Daftar Bank Semua Entitas",
      {
        children: ["Proses Kalkulasi Biaya Persediaan", "Proses Tutup Buku Akhir Periode", "Perubahan Periode Akuntansi", "Proses Tutup Tahun"],
        label: "Proses Periodik",
      },
      "Proses Tutup Penjualan Tunai (POS)",
    ],
  },
  {
    icon: ShoppingCart,
    label: "Procurement",
    subItems: [
      "Form Pengadaan Barang (FPB)",
      {
        children: ["FPAC Kontrak", "FPAC Non Kontrak"],
        label: "Form Pembelian Antar Cabang (FPAC)",
      },
      "Pra Permintaan Pembelian (Pra PP)",
      "Permintaan Pembelian (PP)",
      "Order Pembelian (PO)",
      "Surat Pengambilan Barang (SPB)",
      "Faktur Pembelian (FB)",
      "Target Pembelian",
      "Informasi Detail Supplier",
      "Analisa Pembelian",
      {
        children: [
          "Daftar Barang",
          "Daftar Kantor",
          "Daftar Pabrik",
          "Memo Permintaan Cabang (MPC)",
          "Order Pembelian Terbuka (POT)",
          "Realisasi Permintaan Cabang (RPC)",
        ],
        label: "Administrasi Pengadaan Barang",
      },
      "Laporan Administrasi Pengadaan",
      "Form Delivery Order (FDO)",
      "Form Barang Masuk (FBM)",
      "Realisasi Pembayaran Ekspedisi (RPE)",
      "Realisasi Berita Acara (RBA)",
      "Form Pengajuan Mutasi Barang (FPMB)",
    ],
  },
  {
    icon: Boxes,
    label: "Inventory",
    subItems: [
      "Penerimaan Barang (PB)",
      "Kerusakan Barang (KB)",
      "Perubahan Status Barang (PSB)",
      "Memo Pengembalian Barang (MPB) - (Memo Debet)",
      "Surat Jalan (SJ)",
      "Tanda Terima Barang (TTB)",
      "Mutasi Barang (MB)",
      "Penyesuaian dan Rebuild Stok (PS)",
      "Informasi Stok Aktual",
      "Analisa Mutasi Persediaan",
      "Analisa Aktifitas Pengiriman",
      {
        children: ["Lokasi Barang", "Mutasi Barang", "Analisa Mutasi Barang", "Stok dan Harga Jual Aktual"],
        label: "Kartu Stok Gudang",
      },
      {
        children: ["Dashboard Stok Opname", "Jadwal dan Hasil Stok Opname"],
        label: "Stok Opname",
      },
      "Data Besi Kompetitor",
    ],
  },
  {
    icon: Banknote,
    label: "Sales",
    subItems: [
      "Penjualan",
      "Order Penjualan (SO)",
      "Surat Perintah Muat (SPM) - (DO)",
      "Faktur Penjualan Kredit (FPK)",
      "Faktur Penjualan Tunai (FP) - (POS)",
      "Memo Kredit (MK) - (Retur Penjualan Tunai)",
      "Memo Potongan Penjualan (MPP)",
      {
        children: [
          "Target Global Penjualan",
          "Target Detail Penjualan",
          "Target Penjualan",
          "Target vs Realisasi (Per Bulan)",
          "Target vs Realisasi (Per Kuartal)",
          "Target vs Realisasi (Per Tahun)",
          "Target Data View",
        ],
        label: "Target Penjualan",
      },
      {
        children: [
          "Rencana Kunjungan Salesman (RKS)",
          "Hasil Kunjungan Salesman (HKS)",
          "Hasil Kunjungan OM-SPV",
          "Informasi Detail Salesman",
          "Monitoring RKS dan HKS",
          "Tanda Terima dan Opname Faktur",
          "Approval Komisi Salesman",
          "Approval Komisi Salesman (Konsolidasi)",
          "Approval Uang Saku",
          "Approval Pencairan Uang Saku (Konsolidasi)",
          "Monitoring Uang Saku",
        ],
        label: "Performa Salesman",
      },
      "Informasi Detail Customer",
      "Analisa Penjualan",
      "Analisa Channel Healthiness",
      "Analisa Aktifitas Transaksi Penjualan",
    ],
  },
  {
    icon: Calculator,
    label: "Finance & Accounting",
    subItems: [
      {
        children: ["Jurnal Umum (JU)", "Pengeluaran Lain (BK)", "Pemasukan Lain (BM)", "Jurnal HRIS Via API"],
        label: "Penjurnalan",
      },
      {
        children: [
          "Pembayaran Hutang (PHU)",
          "Penerimaan Piutang (PPI)",
          "Pembayaran Hutang Ekspedisi (PHE)",
          "Form Pengajuan Pembayaran (FPP)",
          "Daftar Bukti Tanda Terima Pembayaran (TTP)",
          "Proses Posting TTP",
          "Pembayaran Uang Muka",
          "Konsolidasi PHE",
        ],
        label: "Pembayaran / Penerimaan",
      },
      {
        children: [
          "Buku Besar",
          "Buku Subledger",
          "Rekap dan Detail Mutasi Subledger",
          "Buku Mutasi Kas dan Bank",
          "Buku Mutasi Hutang (AP)",
          "Buku Mutasi Piutang (AR)",
        ],
        label: "Pembukuan",
      },
      {
        children: [
          "Analisa Hutang (AP)",
          "Analisa Pembayaran Hutang",
          "Analisa Piutang (AR)",
          "Analisa Piutang Overdue",
          "Analisa Penerimaan Piutang (Hasil Penagihan)",
          "Analisa Beban Perusahaan",
        ],
        label: "Analisa",
      },
      {
        children: ["Mutasi Bank Via API", "Komparasi Saldo Akhir Sistem dan API Bank", "Rekonsiliasi Bank", "Buku Bank", "Transaksi Bank"],
        label: "Bank",
      },
      {
        children: ["Kas Opname (Cash Count)", "History Jurnal Transaksi", "Informasi Keuangan", "Pembebanan Selisih Barang"],
        label: "Lainnya",
      },
    ],
  },
  {
    icon: FileText,
    label: "Reports",
    subItems: [
      "Pembelian",
      "Hutang Usaha dan Supplier",
      "Penjualan",
      "Piutang Usaha dan Customer",
      "Buku Besar",
      "Laporan Keuangan",
      "Persediaan",
      "Performa Salesman",
      "Laporan Lainnya",
      "Aktiva Tetap",
      "Report Archive Files (*.raf)",
    ],
  },
  {
    icon: LayoutDashboard,
    label: "Dashboard",
    subItems: [
      "Pengadaan",
      "Penjualan",
      "Logistik",
      "Stok",
      "Hutang Dagang (AP)",
      "Piutang Dagang (AR)",
      {
        children: ["Followup Penanganan Piutang (AR)", "Check Data Penerimaan Piutang", "Check Data Faktur Lunas", "Buku Lunas"],
        label: "Reporting",
      },
      "Biaya Operasional Kendaraan",
      "Aktifitas Operasional Kendaraan",
      "Surat Ijin Jalan (Karyawan dan Kendaraan)",
      "Monitor PB dan Dokumen Asli",
      {
        children: [
          "Dashboard KPI Kantor Cabang",
          "Realisasi Penjualan",
          "Stok Overdue",
          "AR Overdue",
          "Penggunaan Kendaraan",
          "Team Bawahan",
          "Laba Rugi",
          "Beban Operasional",
          "Realisasi Penjualan 2023",
        ],
        label: "KPI Kantor Cabang",
      },
      {
        children: [
          "Dashboard KPI OM",
          "Realisasi Penjualan",
          "Stok Overdue",
          "AR Overdue",
          "Penggunaan Kendaraan",
          "Team Bawahan",
          "Laba Rugi",
          "Beban Operasional",
          "Realisasi Penjualan 2023",
        ],
        label: "KPI Operasional Manager",
      },
      "KPI Supervisor",
      {
        children: [
          "Dashboard KPI Supervisor",
          "Dashboard KPI Salesman",
          "Realisasi Penjualan",
          "Realisasi Kunjungan",
          "Realisasi Efektif Call",
          "AR Overdue",
          "Dashboard KPI Supervisor 2023",
          "Dashboard KPI Salesman 2023",
          "Realisasi Penjualan 2023",
        ],
        label: "KPI Salesman",
      },
      {
        children: [
          "Dashboard KPI Gudang",
          "Hitung dan Rencek",
          "Gudang Transit",
          "Ketepatan Kirim Laporan Opname",
          "Kesesuaian Stok Opname",
          "Pengunaan Kendaraan",
        ],
        label: "KPI Gudang",
      },
      "Klaim Barang Kurang (DPP) - BA",
      "Komparasi Budget Tahunan",
      {
        children: ["Dashboard Stok Overdue", "Rekapitulasi Stok Overdue"],
        label: "Stok Overdue",
      },
      "Pre Order Cabang",
      {
        children: [
          "Perhitungan Dasar Harga Jual Minimal",
          "Simulator Harga Minimal Standar",
          "Price List Per Customer",
          "Price List General",
          "List Sket dan Berat Item",
        ],
        label: "Standar Harga Jual",
      },
    ],
  },
  {
    icon: Combine,
    label: "Consolidation",
    subItems: [
      "Keuangan",
      "Pembelian",
      {
        children: ["Info Gudang Konsolidasi", "Pengiriman Barang Pabrik dan Tonase", "Konsolidasi Hitung dan rencek"],
        label: "Logistik",
      },
      {
        children: ["Daftar PO Outstanding", "Breakdown PO Outstanding"],
        label: "PO Outstanding",
      },
      {
        children: ["Realisasi Per Bulan", "Realisasi Per Kuartal"],
        label: "Target dan Realisasi Penjualan",
      },
      {
        children: ["Stok Konsolidasi", "Analisa Stok Konsolidasi", "Rekapitulasi Harian Mutasi Barang", "Jadwal dan Hasil Stok Opname"],
        label: "Stok",
      },
      "Re-Order Point",
      {
        children: [
          "KPI Kantor Cabang",
          "KPI Operasional Manager",
          "KPI Salesman",
          "KPI Supervisor",
          "KPI Gudang",
          "KPI Salesman 2023",
          "KPI Supervisor 2023",
        ],
        label: "Rangking KPI",
      },
      "Klaim Barang Kurang (DPP) - BA",
      "Laporan Keuangan",
      "Realisasi Pembayaran Ekspedisi (RPE)",
      "Realisasi Berita Acara (RBA)",
      "Data Besi Kompetitor",
      "Informasi Daftar Customer",
      "Transaksi PS dan Stok BS",
    ],
  },
];

export const ORDER_PEMBELIAN_DATA = [
  {
    beratKg: 4900,
    biayaPengiriman: null,
    estimasiPengiriman: new Date("2021-05-31"),
    nettoMU: 77625000,
    nomorPO: "2102.0910.00022",
    pajak: "Tanpa Pajak",
    statusApproval: "Disetujui",
    statusDokumen: "Tertutup",
    supplier: "KENCANA PUSAT",
    tanggal: new Date("2021-05-24"),
    tanggalBerlaku: new Date("2021-05-31"),
    termin: "Net 1",
  },
  {
    beratKg: 11790,
    biayaPengiriman: null,
    estimasiPengiriman: new Date("2021-06-09"),
    nettoMU: 136626050,
    nomorPO: "2102.0910.00023",
    pajak: "Tanpa Pajak",
    statusApproval: "Disetujui",
    statusDokumen: "Tertutup",
    supplier: "KENCANA PUSAT",
    tanggal: new Date("2021-05-24"),
    tanggalBerlaku: new Date("2021-05-31"),
    termin: "Net 1",
  },
  {
    beratKg: 18850,
    biayaPengiriman: null,
    estimasiPengiriman: new Date("2021-06-03"),
    nettoMU: 49049000,
    nomorPO: "2102.0910.00025",
    pajak: "Tanpa Pajak",
    statusApproval: "Disetujui",
    statusDokumen: "Tertutup",
    supplier: "KENCANA PUSAT",
    tanggal: new Date("2021-05-27"),
    tanggalBerlaku: new Date("2021-05-30"),
    termin: "Net 1",
  },
  {
    beratKg: 30500,
    biayaPengiriman: null,
    estimasiPengiriman: new Date("2021-06-03"),
    nettoMU: 76440000,
    nomorPO: "2102.0910.00026",
    pajak: "Tanpa Pajak",
    statusApproval: "Disetujui",
    statusDokumen: "Tertutup",
    supplier: "KENCANA PUSAT",
    tanggal: new Date("2021-05-27"),
    tanggalBerlaku: new Date("2021-06-03"),
    termin: "Net 1",
  },
  {
    beratKg: 7475,
    biayaPengiriman: null,
    estimasiPengiriman: new Date("2021-06-02"),
    nettoMU: 156875000,
    nomorPO: "2102.0910.00029",
    pajak: "Tanpa Pajak",
    statusApproval: "Disetujui",
    statusDokumen: "Tertutup",
    supplier: "KENCANA PUSAT",
    tanggal: new Date("2021-05-28"),
    tanggalBerlaku: new Date("2021-06-04"),
    termin: "Net 1",
  },
  {
    beratKg: 8200,
    biayaPengiriman: null,
    estimasiPengiriman: new Date("2021-06-02"),
    nettoMU: 187600000,
    nomorPO: "2102.0910.00030",
    pajak: "Tanpa Pajak",
    statusApproval: "Disetujui",
    statusDokumen: "Tertutup",
    supplier: "KENCANA PUSAT",
    tanggal: new Date("2021-05-28"),
    tanggalBerlaku: new Date("2021-06-04"),
    termin: "Net 1",
  },
  {
    beratKg: 20150,
    biayaPengiriman: null,
    estimasiPengiriman: new Date("2021-06-07"),
    nettoMU: 53824900,
    nomorPO: "2102.0910.00031",
    pajak: "Tanpa Pajak",
    statusApproval: "Disetujui",
    statusDokumen: "Tertutup",
    supplier: "KENCANA PUSAT",
    tanggal: new Date("2021-05-28"),
    tanggalBerlaku: new Date("2021-06-04"),
    termin: "Net 1",
  },
];
